# Generated by Django 4.0.6 on 2022-07-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activofijo',
            name='is_consiliacion_completa',
            field=models.BooleanField(default=False),
        ),
    ]
